apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-ops-assignment-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-ops-app
  template:
    metadata:
      labels:
        app: ml-ops-app
    spec:
      containers:
      - name: mlops
        image: vegabond/mlops_model:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ml-ops-assignment-service
spec:
  type: NodePort
  selector:
    app: ml-ops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
